version: 2

sources:
  - name: bronze
    schema: gz_raw_data
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: Greenweez sales, one row per product_id for each order_id
        freshness: 
          warn_after: {count: 90, period: day}
        loaded_at_field: "CAST(date_date AS TIMESTAMP)"
        
        columns:
          - name: date_date
            description: date of purchase
          - name: orders_id
            description: unique identifier of the order. foreign key to ship
          - name: products_id
            description: foreign key to product
          - name: revenue
            description: the amount paid by the customer to purchase the product. revenue = quantity * selling price
          - name: quantity
            description: quantity of products purchased in the order
        tests:
          - unique:
              column_name: "(orders_id || '-' || pdt_id)"
      - name: product
        identifier: raw_gz_product
        description: list of products sold by Greenweez
        columns:
          - name: products_id
            description: primary key
            tests:
              - unique
              - not_null
          - name: purchase_price
            description: product purchasing price     
      - name: ship
        identifier: raw_gz_ship
        description: Greenweez shipping fees and costs per order
        columns:
          - name: orders_id
            description: primary key
            tests:
              - unique
              - not_null
          - name: shipping_fee
            description: the price that the customer pays for shipping
          - name: log_cost
            description: the cost of fulfilling each order
          - name: ship_cost
            description: what Greenweez pays to the carrier for their shipping service
      
      - name: adwords
        identifier: raw_gz_adwords
        description: adwords data
      
      - name: bing
        identifier: raw_gz_bing
        description: bing data
      
      - name: criteo
        identifier: raw_gz_criteo
        description: criteo data
      
      - name: facebook
        identifier: raw_gz_facebook
        description: facebook data
      
      - name: int_campaigns
        description: data from all campaigns
        tests:
          - unique:
              column_name: "(campaign_key || '-' || date_date)"
          - not_null:
              column_name:
                - paid_source
                - campaign_name